Doctor/Controllers/PatientInformationController.cs
using BusinessObjectLayer.BusinessEntities;
using DataService.ServiceAbstract;
using Doctor.Filters;
using System.Collections.Generic;
using System.Web.Mvc;
using System;
using DataProvider.ModelAbstract;
using DataProvider.CustomeModel;
using DataProvider;
using System.Web.Routing;
using DataService.CommanClass;
namespace Doctor.Controllers
{

    public class PatientInformationController : Controller
    {
        // GET: PatientInformation
        private readonly IPatient _patient;
        private readonly IProcessDetails _processDetails;
        private readonly ICasePaper _casePaper;
        public PatientInformationController(IPatient patient, IProcessDetails processDetails, ICasePaper casePaper)
        {
            _processDetails = processDetails;
            _patient = patient;
            _casePaper = casePaper;
        }

        //[Route("PatientInformation/plist")]
        [AllowAnonymous]
        [CustomFilter]
        public ActionResult Index()
        {
            if (Session["UserName"] != null)
            {
                PatientModel patient = new PatientModel();
                List<PatientModel> list = _patient.PatientList();
                //ViewBag.PatientList = list;
                patient.plist = list;
                return View(patient);
            }
            else
            {
                return RedirectToAction("UserLogin", "Login");
            }
        }

        [AllowAnonymous]
        [CustomFilter]
        [HttpPost]
        public ActionResult Add(PatientModel model)
        {
            bool result = _patient.AddPatient(model);
            //new DataService.CommanClass.CommanEntity<PatientModel>().Save(model);

            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Index");
            }
        }
        //[Route("PatientInformation/Add")]
        [AllowAnonymous]
        [CustomFilter]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            List<PatientModel> list = _patient.PatientList();
            ViewBag.PatientList = list;
            PatientModel patient = _patient.EditPatientByID(id);
            return View(patient);
        }

    
        [CustomFilter]
        [HttpPost]
        public ActionResult Edit(PatientModel patient)
        {
            int result = _patient.EditPatient(patient);
            if (result == 1)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult AppointmentName(string name)
        {
            PatientModel patient = new PatientModel();
            List<PatientModel> pList = _patient.SearchByUserName(name);
            patient.plist = pList;
            return PartialView("pv_PatientList", patient);
        }


        public ActionResult AppointmentDate(DateTime date)
        {
            PatientModel patient = new PatientModel();
            List<PatientModel> pList = _patient.SearchByAppDate(date);
            patient.plist = pList;
            return PartialView("pv_PatientList", patient);
        }

        public ActionResult Appointment(int id)
        {
            List<PatientModel> plist = _patient.BookAppintment(id);
            ViewBag.PatientName = plist;
            ProcessTypeCustomeModel obj = new ProcessTypeCustomeModel()
            {
                PatientId = id
            };
            return View(obj);
        }

        [HttpPost]
        public ActionResult Appointment(ProcessTypeCustomeModel obj)
        {
            int result = _processDetails.AddProcessType(obj);
            if (result > 0)
            {
                return RedirectToAction("Index");
                ViewBag.Msg = "Record Insert";
            }
            else
            {
                return RedirectToAction("Appointment");
            }
        }

        [HttpGet]
        public ActionResult GetCasePapere()
        {
            CasePaperModel casePaper = new CasePaperModel();
            casePaper.pList = _casePaper.PatientList();
            return View(casePaper);
        }

        [HttpPost]
        public ActionResult AddCasePaper(CasePaperModel casePaperModel)
        {
            int result = _casePaper.AddCasePaper(casePaperModel);
            if (result > 0)
            {
                ViewBag.Mag = "Info Added Successfully";
            }
            else
            {
                ViewBag.Msg = "Info Faild To Add";
            }
            return View();
        }

    }
}

Doctor/Views/PatientInformation/Appointment.cshtml
@model DataProvider.CustomeModel.ProcessTypeCustomeModel
@using DataProvider

@section Scripts {

    @Scripts.Render("~/bundles/jqueryui")
    @*@Styles.Render("~/Content/cssjqryUi")*@
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });
        });
    </script>
}


<div class="container">
    @{ if (ViewBag.Msg != null)
        {
            var result = ViewBag.Msg;
            <h4>@result</h4>
        }
    }
</div>
0
@using (Html.BeginForm("Appointment", "PatientInformation", FormMethod.Post))
{
    <div class="jumbotron">
        <div class="container">
            @*<div class="row">
                    <div class="form-group">
                        <label>Patient Name</label>
                        @foreach (var i in (List<BusinessObjectLayer.BusinessEntities.ProcessTypeModel>)ViewBag.PatientName)
                        {
                            <h4>@i.Name</h4>
                            <span id="pid" style="display:none;visibility:hidden">@i.Id</span>
                        }

                    </div>
                </div>*@

            @*<div class="row">
                    <div class="form-group">
                        <label>ProcessType</label>
                        @Html.DropDownListFor(model => model.ProcessTypeId,, new { @class = "form-control" })
                    </div>
                </div>*@

            @*@Html.HiddenFor(f=>f.PatientId==Model.PatientId)*@
            <div class="row">
                <div class="form-group">
                    <label>Fees</label>
                    @Html.TextBoxFor(model => model.Fees, new { @class = "form-control" })
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <label>Next AppointMent</label>
                    @Html.TextBoxFor(model => model.NextAppointment, new { @class = "form-control", @type = "datetime" })
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <label>DiagnosisType</label>
                    @Html.TextBoxFor(model => model.DiagnosisType, new { @class = "form-control" })

                </div>
            </div>

            @*<div class="row">
                    <div class="form-group">
                        <label>Diagnosis</label>
                        @Html.TextBoxFor(model => model.Diagnosis, new { @class = "form-control" })
                    </div>
                </div>*@

            <div class="row">
                <div class="col-lg-2">
                    <input type="submit" value="Add" class="btn btn-success">
                </div>

                <div class="col-lg-2">
                    <input type="reset" value="Cancel" name="Cancle" class="btn btn-warning" />
                </div>
            </div>
        </div>
    </div>
}

Doctor/Views/PatientInformation/Edit.cshtml
@model BusinessObjectLayer.BusinessEntities.PatientModel


@section Scripts {

    @Scripts.Render("~/bundles/jqueryui")
    @*@Styles.Render("~/Content/cssjqryUi")*@
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });
        });
    </script>
}


<!-- Modal -->
@using (Html.BeginForm("Edit", "PatientInformation", FormMethod.Post))
{
    <div class="jumbotron">
        <div class="container">

            <div class="row">
                <div class="form-group">
                    <label>Name</label>
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <label>Address</label>
                    @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <label>AppointMent Date&Time</label>
                    @Html.TextBoxFor(model => model.AppointMent, "{0:MM\\/dd\\/yyyy}", new { @class = "form-control", @type = "datetime" })
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label>password</label>
                    @Html.TextBoxFor(model => model.Passwoard, new { @class = "form-control" })
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label>Diagnosis</label>
                    @Html.TextBoxFor(model => model.Diagnosis, new { @class = "form-control" })
                </div>
            </div>

            <div class="row">
                <div class="col-lg-2">
                    <input type="submit" value="Add" class="btn btn-success">
                </div>

                <div class="col-lg-2">
                    <input type="reset" value="Cancel" name="Cancle" class="btn btn-warning" />
                </div>
            </div>

        </div>
    </div>
}

Doctor/Views/PatientInformation/GetCasePapere.cshtml
@model BusinessObjectLayer.BusinessEntities.CasePaperModel


@using (Html.BeginForm("AddCasePaper", "PatientInformation", FormMethod.Post))
{
<div class="container">
    <div class="form-horizontal">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <label>Select Pationt:</label>
                @Html.DropDownListFor(f => f.patientID, new SelectList(Model.pList, "ID", "Name"), "--Select Patinet--")
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-horizontal">
            <div class="col-md-6,col-sm-6">
                <label>Visited:</label>
                @Html.RadioButtonFor(n => n.Vistited, "FirstTime") <label>FirstTime</label>
                @Html.RadioButtonFor(n => n.Vistited, "SecondTime")<label>SecondTime</label>
            </div>
            <div class="col-md-6 col-sm-6">
                <label>Gender:</label>
                @Html.RadioButtonFor(n => n.Gender, "Male")<label>Male</label>
                @Html.RadioButtonFor(n => n.Gender, "Female")<label>Female</label>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="form-horizontal">
            <div class="col-md-12 col-sm-12">
                <label>Details:</label>
                @Html.TextAreaFor(f => f.Details, new { @class = "whatever-class", @cols = 80, @rows = 10 })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-horizontal">
            <div class="col-md-12 col-sm-12">
                <label>Details:</label>
                @Html.TextAreaFor(f => f.Digonostic, new { @class = "form-control", @cols = 100, @rows = 10 })
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-5 col-sm-5">
            <input type="submit" value="Send" class="btn btn-success" />
            <input type="reset" value="Reset" class="btn btn-warning" />

        </div>
    </div>
</div>
}

Doctor/Views/PatientInformation/Index.cshtml
@model BusinessObjectLayer.BusinessEntities.PatientModel
@{
    ViewBag.Title = "Index";
}
<style type="text/css">
    .editButton {
        background: url('../../Images/editbton.jpg') no-repeat top left;
        display: block;
        width: 80px;
        height: 80px;
    }
</style>
<script src="~/Scripts/jquery-1.12.4.js"></script>
@section Scripts {

    @Scripts.Render("~/bundles/jqueryui")
    @*@Styles.Render("~/Content/cssjqryUi")*@
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });
        });
    </script>
}
<br />
<br />
<div class="container">
    <div class="row">
        <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal">Create Patient</button>
    </div>

    <br />

    <!-- Modal -->
    @using (Html.BeginForm("Add", "PatientInformation", FormMethod.Post))
    {
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                @Html.ValidationSummary(true)
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">@Html.ActionLink("Index", "Doctor")</h4>
                    </div>
                    <div class="modal-body">
                        <div class="container">
                            <div class="row">
                                <div class="form-group">
                                    <label>Name</label>
                                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group">
                                    <label>Password</label>
                                    @Html.TextBoxFor(model => model.Passwoard, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(v => v.Passwoard, "Enter Passwoard", new { @claas = "text-danger" })
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group">
                                    <label>Address</label>
                                    @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                                </div>
                            </div>


                            <div class="row">
                                <div class="form-group">
                                    <label>AppointMent Date&Time</label>
                                    @Html.TextBoxFor(model => model.AppointMent, new { @class = "form-control", @type = "datetime" })

                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group">
                                    <label>Diagnosis</label>
                                    @Html.TextBoxFor(model => model.Diagnosis, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-2">
                                    <input type="submit" value="Add" class="btn btn-success">
                                </div>

                                <div class="col-lg-2">
                                    <input type="reset" value="Cancel" name="Cancle" class="btn btn-warning" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
    }

</div>
<div class="container">
    <div class="row">
        <div class="col-md-3 col-sm-3">
            Name:<input type="text" class="form-control" id="txtName" />
        </div>
        <div class="col-md-3 col-sm-3">
            Date:<input type="text" class="form-control" id="txtDate" />
        </div>
    </div>
    <div class="">
        <div class="col-md-12 col-sm-12">
            <br />
            <div id="">
                @Html.Partial("~/Views/Shared/pv_PatientList.cshtml")
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
                        debugger;
        $("#txtName").keyup(function () {
            var name = $("#txtName").val();
            if (name != null) {
                $.ajax({
                    url: '@Url.Action("AppointmentName", "PatientInformation")',
                    data: { 'name': name },
                    type: "get",
                    contenttype: 'application/json; charset=utf-8',
                    async: true,
                    success: function (data) {
                        console.log(data);
                        $("#grr").html(data);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert("Something Went Wrong");
                    }
                });
            }
            else {
                alert("Enter The Name");
            }
        });

</script>
<script type="text/javascript">
    $(document).ready(function () {

        $("#txtDate").keyup(function () {
            var date = $("#txtDate").val();

                $.ajax({
                    url: '@Url.Action("AppointmentDate", "PatientInformation")',
                    data: { 'date': date },
                    type: "get",
                    contenttype: 'application/json; charset=utf-8',
                    async: true,
                    success: function (data) {
                        $("#grr").html(data);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert("Something Went Wrong");
                    }
                });

        });

    })
</script>