Doctor/Controllers/LoginController.cs
using BusinessObjectLayer.BusinessEntities;
using DataService.ServiceMethod;
using DataService.ServiceAbstract;
using System.Web.Mvc;
using System.Web.Security;
namespace Doctor.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        User user = new User();
        IUser _iUser;
        IEmailSendnig _emailSendnig;
        public LoginController(IUser iiuser, IEmailSendnig emailSendnig)
        {
            this._iUser = iiuser;
            this._emailSendnig = emailSendnig;
        }

        public ActionResult UserLogin()
        {
            // Session.Abandon();
            //Session.Clear();
            return View(new UsersModel());
        }

        [HttpPost]
        public ActionResult UserLogin(UsersModel users)
        {
            var usersModel = user.IsExist(users);
            if (!Equals(usersModel, null))
            {
                Session["Emaill"] = usersModel.Emaill;
                Session["RoleId"] = usersModel.RoleId;
                Session["UserId"] = usersModel.Id;
                _emailSendnig.SendEmail(users.Emaill);
                return RedirectToAction("Index", "PatientInformation");
            }
            else
            {
                ViewBag.Message = "UserID/Password Invalid";
            }

            return View();
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            //  Session.Clear();
            FormsAuthentication.SignOut();
            return RedirectToAction("UserLogin");
        }

        public ActionResult NotAllow()
        {
            return View();
        }

        public ActionResult forgoatPassword()
        {
            return View(new UsersModel());
        }

        [HttpPost]
        public ActionResult forgoatPassword(UsersModel usersModel)
        {

            ModelState.Remove(usersModel.CompairPassword);
            //   ModelState.Remove(usersModel.UserName);/

            if (!string.IsNullOrEmpty(usersModel.Name))
            {
                int result = _iUser.ChangePassword(usersModel);
                if (result > 0)
                {
                    return RedirectToAction("Index", "PatientInformation");
                }
            }
            else
            {
                return RedirectToAction("forgoatPassword");
            }
            return View(usersModel);
        }

    }
}

Doctor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                </ul>
                <div class="row" style="float:right;margin-top:15px">
                    @if (Session["UserName"] != null)
                    {
                        <h4 style="background-color:aqua">Welcome:@Convert.ToString(Session["UserName"])</h4>
                        @Html.ActionLink("Logout","Logout","Login",null, new { @class = "btn-warning" })

                    }

                    else
                    {

                        @Html.ActionLink("Login", "UserLogin", "Login", null, new { @class = "btn-success" })

                    }
                </div>
            </div>


        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Doctor/Views/Shared/pv_PatientList.cshtml
@*@model IEnumerable<BusinessObjectLayer.BusinessEntities.PatientModel>*@
@using BusinessObjectLayer.BusinessEntities
@model PatientModel

@{
    List<PatientModel> patientModels = Model.plist.Take(1).ToList();
}
<div class="">
    @*<div id="tblPatient">
            <table class="table table-bordered">
                <tr class="text-info">
                    <td>Name</td>
                    <td>Address</td>
                    <td>AppointmentTime</td>
                    <td>diagnosis</td>
                    <td>Action</td>
                    <td>Book Appointment</td>
                </tr>

                @foreach (var i in Model)
                {
                    <tr>
                        <td>@i.Name</td>
                        <td>@i.Address</td>
                        <td>@i.AppointMent</td>
                        <td>@i.Diagnosis</td>
                        <td><a href='@Url.Action("Edit", new { Id = i.Id })'> <img src="../../Images/editbton.jpg" height="20" width="20"></a></td>
                        <td><a href='@Url.Action("Appointment", new { Id = i.Id })'><img src="../../Images/appot.jpg" height="20" width="20"></a></td>
                    </tr>
                }
            </table>
        </div>*@



    @{
        var dd = new WebGrid(canSort: true, canPage: true, rowsPerPage: 2, ajaxUpdateContainerId: "grr");
        dd.Bind(Model.plist);
        dd.Pager(WebGridPagerModes.All);

    }

    @dd.GetHtml(tableStyle: "table table-bordered", htmlAttributes: new { id = "grr" },
                                                 columns: dd.Columns(
                                                  dd.Column("Name", "Address", format: @<text>@item.Name</text>),
                                                  dd.Column("Address", "Address", format: @<text>@item.Address</text>),
                                                   dd.Column("AppointMent", "AppointMent", format: @<text>@(item.AppointMent)</text>),
                                                                                                                                                                        dd.Column("Diagnosis", "Diagnosis", format: @<text>@(item.Diagnosis)</text>),
                                                                                                                                                                                                                dd.Column("IsDoctor", "IsDoctor", format: @<text><input name="chkUserAdminGroup" type="checkbox" id="isdoctor" value="@item.IsDoctor" @(item.IsDoctor == true ? null : "unchecked") /></text>)

                                                                                                                                                                                                                                ))
</div>
<script src="~/Scripts/jquery-1.12.4.js"></script>